name: portfolio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  lottie: ^2.3.2
  smooth_page_indicator: ^1.0.1
  url_launcher: ^6.1.10
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/anim/
    - assets/img/
    - assets/vids/
